# 异常捕获

## 抛出异常

从本质上来说，异常就只是一个对象。并且，我们也可以自定义自己的异常类。所有的异常类都继承自同一个内置类`BaseException`。

在代码中使用`raise`语句可以抛出一个异常。假设一个只能够添加偶数的类：

```python
class EvenOnly(list):
    def append(self, value):
        if not isinstance(value, int):
            raise TypeError("Not an integer")
        if value % 2 != 0:
            raise ValueError("Not an even integer")
        super().append(value)
```

上述代码中当追加的元素不是一个整数的时候，就会抛出一个`TypeError`的异常。当追加的元素不是一个偶数的时候，就会抛出一个`ValueError`的异常。

## 处理异常

显然，如果在使用上述的类的时候，在执行发生异常时程序会直接停止执行。原因很简单，因为程序仅仅抛出了异常，而没有捕获它并且进行处理。将可能会发生异常的代码包裹在`try...except`语句中来捕获并且处理异常：

```python
try:
    # some statements may cause exceptions
except:
    # deal with the exceptions
# statements after the exceptions' handling
```

然而，上面的语句会捕获所有的异常。如果我们需要只捕获特定的异常来处理，而将其他的异常交给控制台来处理，那么就需要在`except`语句后面指定异常的类型：

```python
try:
    # some statements may cause exceptions
except ZeroDivisionError:
    # deal with the ZeroDivisionError exceptions
# statements after the exceptions' handling
```

可以使用`as`关键字来引用抛出得到的异常：

```python
except ZeroDivisionError as e:
```

这种情况一般用在自定义的异常类时使用，需要调用一些自定义的方法。

`except`语句也可以叠加起来使用，当出现异常时，按照从上往下的顺序来进行匹配。如果想要针对某种异常进行某些操作再上传给上层的函数处理，可以使用`raise`关键字而不使用任何参数来完成：

```python
try:
    # some statements may cause exceptions
except ZeroDivisionError:
    # deal with the ZeroDivisionError exceptions
except TypeError:
    # deal with the TypeError exceptions
except ValueError:
    # some operations
    raise
# statements after the exceptions' handling
```

存在一个问题，如果匹配了一个异常，比如`ZeroDivisionError`，那么在之后的异常都不会再被匹配，即使有多个对应的异常也不行。要出现多个异常同时匹配的情况，可以考虑一个因素：所有的异常都是对象，因此存在一些异常的父类。如果想要对特定的几个异常进行处理，然后其他类型的异常统一处理，只需要在处理完所有的特定类型的异常后，捕获`Exception`即可。

`finally`用于指定无论是否遇到异常都会执行的代码。`else`用于指定当没有遇到异常时会执行的代码：

```python
try:
    # some statements may cause exceptions
except ZeroDivisionError:
    # deal with the ZeroDivisionError exceptions
except TypeError:
    # deal with the TypeError exceptions
except ValueError:
    # deal with the ValueError exceptions
else:
    # if no exception, execute these statements
finally:
    # weather there are exceptions or not, always execute these statements
```

`finally`下的语句无论在是否有异常的情况下都会执行，一些常见的放在`finally`下的处理包括：关闭打开的文件、数据库链接、发送关闭握手等等。需要注意的是，如果try当中含有`return`，`finally`下的代码会在返回值之前执行。`finally`分支总是会被执行，不管异常有没有发生。当异常在`try`部分发生，但是没有被`except`分支处理（或者在`except`或`else`分支发生），这个异常会在`finally`分支执行之后，被re-raised。当`try`部分有`break`，`continue`或者`return`语句时，`finally`一样会在离开`try`的时候被执行。

## 异常的层级

大部分的异常都是`Exception`类的子类。`Exception`类继承自`BaseException`类。所有的异常都必须继承`BaseException`类或者其子类。有三种异常类直接继承`BaseException`：`Exception`、`SystemExit`以及`KeyboardInterrupt`。

当仅仅使用`except:`语句的时候，就会捕获所有`BaseException`的子类。

## 自定义异常

自定义自己的异常很简单，比如只需要继承`Exception`类即可，甚至不需要往其中添加任何内容。`Exception`类的`__init__()`方法设计成能够继承任意参数并将它们作为一个元组保存在`args`的属性中。这样甚至可以不需要自定义`__init__()`方法而实现自己的异常类。

当然，你也可以自定义自己的异常类，以及其中的`__init__()`方法：

```python
class TooLargeError(Exception):
    def __init__(self, room, size):
        super().__init__("cause a TooLargeError")
        self.room = room
        self.size = size

    def overage(self):
        return self.size - self.room
```
